### ISSUE TITLE
Ability to control mutation behavior,  extend the evolution simulation.

### ISSUE THREAD

**Issue by ACIIL** [synkarius/saltbot#120]
I am looking for ways to help the simulator to get out Local maxima solution.  Studying how  the mutation chance, mutation change difference, and population count are handled i see they are hard-coded and may have issues.  Can these constants they be placed in a local script and as a variable for easy changing? Also there maybe a serious mutation error written below.

Justification is how rarely i see the solution get out of a maxima, things to note that would improve the simulation in [Chromosome.prototype.mate]:
1) when the simulation does not change over time, upping the mutation chance, even above 50%, can add some chaos need to get out of the maxima (and i can do this in console, for the sesson), but...
2) Even then, the change right now can only go in a range of 0% to 200% of the current  There are Actually multiple problems here;  the values are multiplicative, which means there is an EXTREME bias to notch the current value towards zero. In contract, a 200% chance is tiny  compared to approaching zero. Allows this max % value to go higher by user would would help find larger value weights, although there is is a bigger problem with that 0%. 
3) Population count, well 100 hard-coded should work, a higher critter space in the evolution sim can help in ways related to o()  and expanding trials. Changing this population value is in [Simulator.prototype.initializePool] in the for loop.

As for #2,  as i write this and notice the multiplication, you may want to change the last line to such that it ultimately  + or -  the random value on the original value, that should solve the the values iterating  towards zero as the simulation runs. There should be a few evo. sim examples online if you need tips.  I have a bit of experience with this kind of code.

**Comment by ACIIL** [comment]
I made a example edit for the mutation to solve the problem #2 with multiplication. Here:
https://github.com/ACIIL/saltbot/commit/4f20cff56ec01d27b7b44b8da17c82df6215e923

Now i would test this but there is a error with resetting  a new pool from a fresh local extension loaded from a local folder. The error is:
```
popup.js:468 Uncaught ReferenceError: Chromosome is not defined
    at Simulator.initializePool (popup.js:468)
    at HTMLDivElement.<anonymous> (popup.js:529)
```
My best guess is the given manifest or something is not opening strategy.js where the Chromosome structure defined for me.  Any ideas?

I wanna test this change, i am not that experienced with extension coding so it all practice experience to me at the moment.

**Comment by ACIIL** [comment]
Nevermind that error, no float notation allowed. Now testing the mutation change...

**Comment by reconman** [comment]
I've used dynamic mutation rates in a university course before so I now know a fair share about it too and the original mutation code is from synkarius so I didn't really touch it because it was working as it was.

If you want to optmize the mutation process go ahead. You're right, the 0 % to 200 % change really needs to be changed. Most chromosome values are <= 0.1 because of it.

**Comment by ACIIL** [comment]
Success with my suggested changes to mutations, see my fork of saltbot. It should be trial ready. 
Example chromosome behavior, mind you it ran 25-40 generations:
```

chromosome:
oddsWeight : 0.00010210563154774701
timeWeight : 0.017201336522997532
winPercentageWeight : 0.019941702352455168
crowdFavorWeight : 0.0004365515263022999
illumFavorWeight : 0.00002497070004185715
wX : 0.0013964410213668683
wS : 0.08320719056321835
wA : 0.10635344517505572
wB : 0.004239331036345775
wP : 0.02573900026531733
wU : 0.004094185495518845
lX : 0.021422024091708403
lS : 0.0010022579271714738
lA : 0.0013105800280132178
lB : 0.027682741586609515
lP : 0.021212188232838974
lU : 0.0795523969534015
oX : 0.03243134906460232
oS : 0.024972428477838607
oA : 0.10043353970497665
oB : 0.0007279324360449069
oP : 0.0027072476516079315
oU : 0.012439738114126513
wtX : 0.01392225729843136
wtS : 0.006248705245044449
wtA : 0.024364309935841162
wtB : 0.03348818403900648
wtP : 0.0005892763440585809
wtU : 0.0061408281481363436
ltX : 0.01231610878389875
ltS : 0.17127659214140284
ltA : 0.06300484704336662
ltB : 0.012576481578362613
ltP : 0.037458971371320246
ltU : 0.0299827535120228
rank : 1 -> 63.5910%,  $48,309,684
popup.js:440 

-------- end of gen100  10, m proc'd w/ CS 37087/37087=100%m -> 63.6%c, $48,309,684   -----------------
```

**Comment by reconman** [comment]
I've edited your changes a bit to create cleaner code and I've changed the normalization to a sum of 1 to a sum of 100 because it's more readable for humans.

https://github.com/synkarius/saltbot/commit/4f76d405285e0ca5fb0cfaadfff6983d14527879

I've created a new branch for the mutation experiments here

https://github.com/synkarius/saltbot/tree/new-mutation-method

With your changes I was able to get estimated earnings of 80 million in 30 long generations instead of 70 million in over 300.

After 30 generations I was pretty much stuck and there were only minor improvements of +20k to +50k now and then.

A higher mutation rate when getting stuck is a good idea but I just found the problem with that approach. The best solution is not calculated based on a fixed set of recorded matches but on a dynamic one. This way wins and losses get added during the calculation of the best chromosome. You can't determine if you're stuck in a local maximum if you don't freeze the match data used for calculating the chromosome.

You need to keep the same match data for all generations and use that to calculate the best chromosome in order to use a dynamic mutation rate.

Maybe I can think of a solution in the next few days.

**Comment by ACIIL** [comment]
What an improvement i hear!    Yeah i noticed similar ramp up to a good solution faster.  I am worried there are other better solutions never found, as a local maxima for the current best solution cannot be pushed away without extreme random changes in weights to trial. The base chromosome weights be might sliding the sim to a predetermined choice. I'll test with a blank default later.

I guess we should move the mutation conversation out of the issues page? Where to? I'll test out this new branch.
Guess my final issues left here is placing the mutation settings into the UI. Cannot say i am experienced doing that.

**Comment by ACIIL** [comment]
A fixed set of recorded matches versus a dynamic one; they have their advantages.  Advantages : Fixed means fixed testing, Dynamic means the sim will have constant new data that applies pressures to the sim each generation in time. 

With the branch i am working on, With what i have I seen as a problem, i see some generations drop off in performance with winnings dropping as high as 1-10% and the correct % no better (hovering 60-65%,  if the data was static i could rule out it being new match data adding new crash to the total, which somehow could create a better score on the next generation,  versus what i think is the best last generation chromosome being forgotten for something worse by mutations, here the current generations' Champions are being forgotten/bread out.
