### ISSUE TITLE
"Update Genetic Weights" Causing lockup

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#139]
From what I can tell, this button does not function correctly on lower end machines. The popup just hangs, and there is no indication that any updates are being applied. 

How would one check that the update is running, and why doesn't it just happen automatically?

**Comment by reconman** [comment]
The default behaviour of high performance tasks in javascript is that it runs on one single thread. As long as that thread is running the GUI won't react.

When you start programming GUIs the first thing you experience is that lockup. The solution is to create a background thread where the calculations are run.

In Chrome creating a background thread is not as easy as it seems. The thread needs to be supplied everything and won't be able to interact with chrome.local.storage or variables of other scripts at all.

About a year ago I tried moving the mutation calculations to another thread but because of the above mentioned difficulties I put it on hold.

**Comment by calexil** [comment]
hmm okay, well I'll leave this open until a solution is reached I guess

**Comment by calexil** [comment]
Wouldn't it be more elegant to have the bot update periodically like every 10 matches or so but only for the first 50 matches or whatever makes sense

**Comment by reconman** [comment]
That would mess up the chromosome badly. It would just optimize for 50 matches it recorded and ignore the rest. Every 10 matches would be quite often so there is a high chance of the chromosome being manipulated.

**Comment by calexil** [comment]
hmm.

**Comment by calexil** [comment]
no solution presented, closing

**Comment by calexil** [comment]
This issue was reported errantly, closing

**Comment by reconman** [comment]
I don't think so and I want to keep this issue open because I may be able to refactor the genetic weight calculations to web workers in the future.
