### ISSUE TITLE
Add option to ignore 0 time records, and option to only store records for a set time(months,weeks)

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#167]
since the main record database is growing out of control for under powered machines, it would make sense to auto trim the records in two ways:

1: Do not store 0-time records

2: Auto trim very old records(3month+)

**Comment by ACIIL** [comment]
0 time records are made in a few cases:
1) match exceeded a maximum amount
2) match was in not matchmaking, eg: tournaments.
3) match was unknown
There also a condition i found confusing where testing against time x1.5 (or something?), think it was for tournaments.

Like i was going in #158, prune records manually. You need to make the choice were too much records is too much.  As you found recorded keeping your specialty with that +5mgs log, I ask you to learn how to prune such files.  

Losing records compounds another problem: training accurate chromosomes with mass data.  @calexil  you will need to learn how this code works, just like us. Please do.

Also this issue is under #158.

**Comment by ACIIL** [comment]
Also another important fact about 0 times. I later found out:

0 times are not pushed in a characters stats, this is good for that data, and bad as the record is completely useless data.

**Comment by calexil** [comment]
OR: conversely we could make this an option

**Comment by ACIIL** [comment]
@calexil i can understand you do not want or understand how to program this, and at the same time i understand you do not understand the code with your own research.  So you must be requesting @synkarius politely to implement this when he has the time. And that is perfectly ok.

**Comment by calexil** [comment]
wow you went from a little condescending.. to extremely condescending 

nice.

**Comment by ACIIL** [comment]
Good to hear you are learning the code. That is exactly what i wanted to hear.  Now back to the issue here.

**Comment by calexil** [comment]
So the data is at over 100k lines now... I cant even import it to a spreadsheet without crashing calc...

**Comment by calexil** [comment]
looks like @reconman  has a plan in the works with indexedDB this fall. Should remove the need for this
