### ISSUE TITLE
Fix '!= should be !==' issue in src\strategy.ts

### ISSUE THREAD

**Issue by calexil** [synkarius/saltbot#195]
[CodeFactor](https://www.codefactor.io/repository/github/synkarius/saltbot) found an issue: != should be !==

It's currently on:
[src\strategy.ts:28
](https://www.codefactor.io/repository/github/synkarius/saltbot/source/master/src/strategy.ts#L28)Commit 0e95b6c4f54b6d1c54da79ce81ee18df6cfbe7b6

**Comment by calexil** [comment]
there are tremendous amount of these errors

**Comment by reconman** [comment]
I know, it's because I switched to Typescript with tslint. They will be fixed in time.

**Comment by reconman** [comment]
Whenever I edit files, Visual Studio shows me the recommendations.

![image](https://user-images.githubusercontent.com/12360257/37926030-8261cbb8-3136-11e8-8966-9e6f8304d497.png)

The findings of CodeFactor are the same as the ones in Visual Studio, because they both rely on TSLint.

I don't see the need to create issues.

**Comment by calexil** [comment]
well i'm fixin em anyways, if you dont want me to then rebase the git from your current pull. 

I was bored
