### ISSUE TITLE
Cant run Update Genetic Weights

### ISSUE THREAD

**Issue by Spoonyman** [synkarius/saltbot#229]
When I try and click it nothing happens and then it freezes the extension up. I was given a file with records so I wanted to get a weight going but its just crashing it out it seems. There were over 500k+ records on the sheet I was given.

**Comment by reconman** [comment]
The freezing of the extension is normal as Javascript has no good way of multi-threading. I'd have to copy all 500,000 records to a worker thread to be able to use a separate CPU thread.

That's why the extension locks up while it's calculating the chromosome values. I can't tell you how long it takes to calculate 1 generation with 500,000 records as I've never had that many records before.

I really wish I could do the calculation in a separate thread easily so the UI doesn't lock up.
