### ISSUE TITLE
Mass Twitch.TV tabs being opened.

### ISSUE THREAD

**Issue by ImSoto** [synkarius/saltbot#35]
twitch_background.js
```
	if (details.getTwitch !== undefined) {
		chrome.tabs.query({
			url : "http://www.twitch.tv/saltybet"
		}, function(result) {
			if (result.length == 0)
				chrome.tabs.create({
					url : "http://www.twitch.tv/saltybet"
				});
		});
	}
});
```

Causes the twitch.tv tab to constantly open, is there any reason for us to open this and have the saltybet page open?

**Comment by synkarius** [comment]
SaltBot opens a separate tab for Twitch in order to read from the chat. Disabling this would disable a lot of the data collection. 

When you say "mass", do you mean that it's opening more than one Twitch tab at a time? The intended behavior is to open the Twitch tab once per minute, but only if it isn't already open.

**Comment by ImSoto** [comment]
Yup that would be my fault, didn't know until I looked at the code it was intentional to open the tab up so I had it being auto blocked and closed.
