### ISSUE TITLE
Request: Lunatic going all in at random

### ISSUE THREAD

**Issue by retsu3** [synkarius/saltbot#74]
This isn't so much a request for people who want to use Saltbot to actually gain profit from it, but rather for people who want to just screw around with it. I'm not sure if this is the right place or not to make a feature request, but it's the only way I can find.

Basically, I would love if there was an option for Lunatic mode where it just went all in every time on a random side. I would love to see how high the bot could go before ultimately failing miserably. I'd code it myself, but I know not a lick of whatever is used to code this, or even how to code in general.

**Comment by Zyrixion** [comment]
It's pretty easy to code in, but I'm not sure an 'all-in a random side every round' feature would be very popular.  It's not actually as exciting as it sounds, since it's just coinflipping it'll fall apart pretty quickly, likely long before getting to exciting quantities of money.  On the other hand, some people have bots dedicated to betting all-in on the upset until they get a win that nets them a sizeable amount of salt (but those bots have illuminati so their bailouts are significantly larger than normal users).

**Comment by synkarius** [comment]
@retsu3, this is the right place to make requests, but I agree with @Zyrixion's comments. A bot which constantly all-in-ed would probably stay within 5-10x the bailout.
