### ISSUE TITLE
Palletes 

### ISSUE THREAD

**Issue by Blix3r** [synkarius/saltbot#77]
Does the bot record palletes used in exhibs or should exhibs be completely unused for data?

**Comment by reconman** [comment]
Palettes are not used in records as most people don't have Illuminati mode to even see them.

Deciding on who to bet based on their wins and their palette is nearly impossible. With several thousand characters and 12 possible palettes which are randomly selected in matchmaking the bot would need a hundredfold of data.

Because palettes can influence character records you could disable the bot for exhibitions with the Toggle Exhibitions button which is temporarily disabled right now.

**Comment by Blix3r** [comment]
Thanks for the info!

**Comment by Blix3r** [comment]
Also is there a way to donate to this project?

**Comment by reconman** [comment]
Donations are not needed since we do it for fun in our leisure time, but thanks for the offer.

**Comment by synkarius** [comment]
Agreed. @Blix3r thank you for the thought though. Glad you like SaltBot that much.
