### ISSUE TITLE
Saltbot Not Betting During Tournaments

### ISSUE THREAD

**Issue by TourneyBug** [synkarius/saltbot#91]
Betting elsewhere seems to work fine, but each match of a tournament produces the following in console:

> Uncaught TypeError: Cannot read property 'src' of undefined       strategy.js:31
> Strategy.getBailout @ strategy.js:31
> Strategy.getBetAmount @ strategy.js:82
> ConfidenceScore.getBetAmount @ strategy.js:373
> Match.betAmount @ tracker.js:93
> (anonymous function) @ tracker.js:140

I assume the bot is still attempting to place a wager and just unable to specify the amount, because a message appears in the betting area along the lines of "please specify a wager amount." Any idea if maybe I've just set something up incorrectly?

**Comment by reconman** [comment]
Do you see a level icon at the top of the saltybet site? It should be to the left of your rank (#xxxx).

**Comment by TourneyBug** [comment]
The issues seems to have resolved itself overnight. Judging from your question, maybe I needed to have placed a prerequisite number of bets for it to have worked? Sorry to have wasted your time, but thank you for your reply and willingness to investigate all the same!

**Comment by reconman** [comment]
The only way I could reproduce that bug was to not have placed 25 or more bets in total. A reload of the site after 25 bets fixed the problem.

---- On Mo, 25 Apr 2016 17:15:49 +0200 notifications@github.com wrote ----

The issues seems to have resolved itself overnight. Judging from your question, maybe I needed to have placed a prerequisite number of bets for it to have worked? Sorry to have wasted your time, but thank you for your reply and willingness to investigate all the same!

**Comment by OldDragon2A** [comment]
I can submit a pull request with a fix for this if you would like?

**Comment by reconman** [comment]
@OldDragon2A Yeah sure, I will not be able to fix it myself until Wednesday night so I'd really appreciate that.
